# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagery',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Photo')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
            bases=('photologue.photo',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='imagery',
            name='tags',
            field=models.ManyToManyField(blank=True, to='images.Tag'),
        ),
    ]
