# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20161022_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
