# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0002_auto_20161120_0010'),
        ('images', '0003_imagery_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='land_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='impart.LandPrice'),
            preserve_default=False,
        ),
    ]
