# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_imagery_land_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagery',
            name='artist',
            field=models.CharField(default='Dirk', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagery',
            name='link',
            field=models.CharField(default='/artist/dirk', max_length=255),
            preserve_default=False,
        ),
    ]
