# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0003_auto_20161222_1952'),
        ('images', '0005_auto_20161221_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impart.LandPrice')),
                ('tags', models.ManyToManyField(blank=True, to='images.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='land_price',
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='link',
        ),
    ]
