# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('images', '0007_auto_20161231_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagery',
            name='photo_ptr',
        ),
        migrations.RemoveField(
            model_name='imagery',
            name='tags',
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='land_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impart.LandPrice'),
        ),
        migrations.DeleteModel(
            name='Imagery',
        ),
    ]
