# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20161231_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
