# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20170105_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name', 'link']},
        ),
    ]
