# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestotheme',
            options={'ordering': ['publication_date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['publication_date'], 'verbose_name_plural': 'News'},
        ),
    ]
