# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0002_auto_20161120_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='namevaluepair',
            name='section',
            field=models.CharField(default='n/a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namevaluepair',
            name='value',
            field=models.CharField(max_length=4096),
        ),
    ]
