# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0003_auto_20161222_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManifestoTheme',
            new_name='Manifesto',
        ),
    ]
