# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("impart", "0004_auto_20170117_0916")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="impart.Artist",
            ),
        )
    ]
