# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0004_auto_20170103_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
