# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0005_news_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifesto',
            options={'ordering': ['publication_date'], 'verbose_name_plural': 'Manifesti'},
        ),
        migrations.AddField(
            model_name='manifesto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
