# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 10:28
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("impart", "0006_auto_20170117_0923")]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="body_dutch",
            field=markdownx.models.MarkdownxField(
                help_text="The news body in Dutch.", max_length=4096
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="body_english",
            field=markdownx.models.MarkdownxField(
                help_text="The news body in English.", max_length=4096
            ),
        ),
    ]
