# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impart', '0006_auto_20170109_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='landprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
