# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("impart", "0009_auto_20170117_2011")]

    operations = [
        migrations.AlterModelOptions(name="landprice", options={"ordering": ["order"]}),
        migrations.AddField(
            model_name="landprice",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
