# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("impart", "0010_auto_20170117_2029")]

    operations = [migrations.RenameModel(old_name="Manifesto", new_name="Manifest")]
