# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("impart", "0014_auto_20170120_1216")]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="section",
            field=models.CharField(
                choices=[
                    ("HO", "Home"),
                    ("NE", "News"),
                    ("AR", "Archive"),
                    ("AN", "News archive"),
                    ("AM", "Manifest archive"),
                    ("MA", "Manifest"),
                    ("LP", "Land Price"),
                    ("AA", "About my art"),
                    ("WO", "Art"),
                    ("CO", "Contact"),
                ],
                max_length=2,
            ),
        )
    ]
