# Generated by Django 3.1.6 on 2021-02-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("impart", "0022_auto_20180807_1107")]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="land_price",
            field=models.ForeignKey(
                help_text="The landprice related with this work of art.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="impart.landprice",
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="materials",
            field=models.CharField(
                blank=True, help_text="The used materials.", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="name",
            field=models.CharField(
                blank=True, help_text="The name of the work of art.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="x",
            field=models.IntegerField(
                blank=True,
                help_text="The number of centimeters on the x-axis.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="y",
            field=models.IntegerField(
                blank=True,
                help_text="The number of centimeters on the y-axis.",
                null=True,
            ),
        ),
    ]
