# Generated by Django 3.1.6 on 2021-02-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("impart", "0023_auto_20210213_1447")]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="land_price",
            field=models.ForeignKey(
                blank=True,
                help_text="The landprice related with this work of art.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="impart.landprice",
            ),
        )
    ]
